[package]
name = "chess"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.22.0"
glam = "0.30.1"
glfw = "0.59.0"
glow = "0.16.0"
image = { version = "0.25.6", default-features = false, features = ["png"] }
